PREFIX rdfs:                       <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:                        <http://www.w3.org/2002/07/owl#>
PREFIX dc:                         <http://purl.org/dc/elements/1.1/>
PREFIX oml:                        <http://opencaesar.io/oml#>

SELECT ?o_iri ?o_title (replace(str(?o_type_iri), "^.*#", "") as ?o_type) ?o_label

WHERE {

	?o_iri a owl:Ontology ;
		dc:title ?o_title ;
		oml:type ?o_type_iri .
		
	OPTIONAL {
		?o_iri rdfs:label ?o_label
	}
}