PREFIX base:                       <http://imce.jpl.nasa.gov/foundation/base#>
PREFIX mission:                    <http://imce.jpl.nasa.gov/foundation/mission#>
PREFIX kpdm-catapult-vocabulary:   <http://opencaesar.io/template/vocabulary/vocabulary#>

SELECT ?c_name

WHERE {
	?c_iri a mission:Component ;
		base:hasCanonicalName ?c_name .
}